name: Bulid with NPM and upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Node sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - run: |
          npm install
          npm run build


      - uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.elec0.com
          username: github-action@apex.elec0.com
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            **/test/**
            **/cypress/**
            **/*.json
            webpack.config.js
            README.md
