name: Cypress Tests with installation job

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: dist

  # run-firefox-tests:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node14.17.0-chrome91-ff89
  #   needs: install
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Download the build folders
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: build
  #         path: dist

  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         # Specify Browser since container image is compile with Firefox
  #         browser: firefox
  #         start: npm start

  run-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start