name: Run Cypress E2E tests

on:
  push:
    branches:
      - '**'
      - '!main' 

jobs:
  cypress-tests-chrome:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.6.0-chrome105-ff104
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install & Run Cypress tests
        uses: cypress-io/github-action@v2.9.7
        with:
          # Disable running of tests within install job 
          build: npm run build
          browser: chrome
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          start: npm start
          config-file: ./cypress.config.ts
