name: Cypress Tests with installation job

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2.9.7
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: dist

  run-firefox-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Install http-server
        run: npm install http-server

      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: firefox
          install: false
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          record: false
          parallel: true
          start: npm start

  run-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Install http-server
        run: npm install http-server

      # Run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
          install: false
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 120
          record: false
          parallel: true
          start: npm start